package in.pervush.leetcode.problems;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * https://leetcode.com/problems/detect-squares/
 */
public class DetectSquares {

    private final Map<Integer, Map<Integer, Integer>> pointsByX = new HashMap<>(); // X -> Y -> count Y
    private final Map<Integer, Map<Integer, Integer>> pointsByY = new HashMap<>(); // Y -> x -> count X

    private static void addPoint(final int x, final int y, Map<Integer, Map<Integer, Integer>> points) {
        points.compute(x, (k, v) -> {
            if (v == null) {
                v = new HashMap<>();
            }
            v.compute(y, (k1, v1) -> v1 == null ? 1 : v1 + 1);
            return v;
        });
    }

    public void add(final int[] point) {
        addPoint(point[0], point[1], pointsByX);
        addPoint(point[1], point[0], pointsByY);
    }

    public int count(final int[] point) {
        final int x1 = point[0];
        final int y1 = point[1];
        int result = 0;

        final var yPoints = pointsByX.getOrDefault(x1, Collections.emptyMap());
        final var xPoints = pointsByY.getOrDefault(y1, Collections.emptyMap());

        for (final var yPoint : yPoints.entrySet()) {
            for (final var xPoint : xPoints.entrySet()) {
                final var point4Cnt = pointsByY.getOrDefault(yPoint.getKey(), Collections.emptyMap())
                        .getOrDefault(xPoint.getKey(), 0);
                final int lengthX = Math.abs(x1 - xPoint.getKey());
                final int lengthY = Math.abs(y1 - yPoint.getKey());
                if (lengthX != lengthY || lengthX == 0 || lengthY == 0) {
                    continue;
                }
                result += point4Cnt * yPoint.getValue() * xPoint.getValue();
            }
        }

        return result;
    }

    public static void test1() {
        final DetectSquares solution = new DetectSquares();
        solution.add(new int[] {3, 10});
        solution.add(new int[] {11, 2});
        solution.add(new int[] {3, 2});
        System.out.println(solution.count(new int[] {11, 10}) + " (1)");
        System.out.println(solution.count(new int[] {14, 8}) + " (0)");
        solution.add(new int[] {11, 2});
        System.out.println(solution.count(new int[] {11, 10}) + " (2)");
    }

    public static void test2() {
        final DetectSquares solution = new DetectSquares();
        solution.add(new int[] {5,10});
        solution.add(new int[] {10,5});
        solution.add(new int[] {10,10});
        System.out.println(solution.count(new int[] {5,5}) + " (1)");
        solution.add(new int[] {3,0});
        solution.add(new int[] {8,0});
        solution.add(new int[] {8,5});
        System.out.println(solution.count(new int[] {3,5}) + " (1)");
        solution.add(new int[] {9,0});
        solution.add(new int[] {9,8});
        solution.add(new int[] {1,8});
        System.out.println(solution.count(new int[] {1,0}) + " (1)");
        solution.add(new int[] {0,0});
        solution.add(new int[] {8,0});
        solution.add(new int[] {8,8});
        System.out.println(solution.count(new int[] {0,8}) + " (2)");
        solution.add(new int[] {1,9});
        solution.add(new int[] {2,9});
        solution.add(new int[] {2,10});
        System.out.println(solution.count(new int[] {1,10}) + " (1)");
        solution.add(new int[] {7,8});
        solution.add(new int[] {2,3});
        solution.add(new int[] {2,8});
        System.out.println(solution.count(new int[] {7,3}) + " (1)");
        solution.add(new int[] {9,10});
        solution.add(new int[] {9,5});
        solution.add(new int[] {4,5});
        System.out.println(solution.count(new int[] {4,10}) + " (1)");
        solution.add(new int[] {0,9});
        solution.add(new int[] {4,5});
        solution.add(new int[] {4,9});
        System.out.println(solution.count(new int[] {0,5}) + " (2)");
        solution.add(new int[] {1,10});
        solution.add(new int[] {10,1});
        solution.add(new int[] {10,10});
        System.out.println(solution.count(new int[] {1,1}) + " (2)");
        solution.add(new int[] {10,0});
        solution.add(new int[] {2,0});
        solution.add(new int[] {2,8});
        System.out.println(solution.count(new int[] {10,8}) + " (2)");
        solution.add(new int[] {7,6});
        solution.add(new int[] {4,6});
        solution.add(new int[] {4,9});
        System.out.println(solution.count(new int[] {7,9}) + " (2)");
        solution.add(new int[] {10,9});
        solution.add(new int[] {10,0});
        solution.add(new int[] {1,0});
        System.out.println(solution.count(new int[] {1,9}) + " (5)");

        solution.add(new int[] {0,9});
        solution.add(new int[] {8,1});
        solution.add(new int[] {0,1});
        System.out.println(solution.count(new int[] {8,9}) + " (6)");
        solution.add(new int[] {3,9});
        solution.add(new int[] {10,9});
        solution.add(new int[] {3,2});
        System.out.println(solution.count(new int[] {10,2}) + " (2)");
        solution.add(new int[] {3,8});
        solution.add(new int[] {9,2});
        solution.add(new int[] {3,2});
        System.out.println(solution.count(new int[] {9,8}) + " (3)");
        solution.add(new int[] {0,9});
        solution.add(new int[] {7,9});
        solution.add(new int[] {0,2});
        System.out.println(solution.count(new int[] {7,2}) + " (3)");
        solution.add(new int[] {10,1});
        solution.add(new int[] {1,10});
        solution.add(new int[] {10,10});
        System.out.println(solution.count(new int[] {1,1}) + " (14)");
        solution.add(new int[] {6,10});
        solution.add(new int[] {2,6});
        solution.add(new int[] {6,6});
        System.out.println(solution.count(new int[] {2,10}) + " (3)");
        solution.add(new int[] {6,0});
        solution.add(new int[] {6,2});
        solution.add(new int[] {8,2});
        System.out.println(solution.count(new int[] {8,0}) + " (1)");
        solution.add(new int[] {6,5});
        solution.add(new int[] {7,4});
        solution.add(new int[] {6,4});
        System.out.println(solution.count(new int[] {7,5}) + " (2)");
        solution.add(new int[] {2,10});
        solution.add(new int[] {8,4});
        solution.add(new int[] {2,4});
        System.out.println(solution.count(new int[] {8,10}) + " (2)");
        solution.add(new int[] {2,6});
        solution.add(new int[] {2,5});
        solution.add(new int[] {1,5});
        System.out.println(solution.count(new int[] {1,6}) + " (4)");
        solution.add(new int[] {10,9});
        solution.add(new int[] {10,0});
        solution.add(new int[] {1,9});
        System.out.println(solution.count(new int[] {1,0}) + " (20)");
        solution.add(new int[] {0,9});
        solution.add(new int[] {5,9});
        solution.add(new int[] {0,4});
        System.out.println(solution.count(new int[] {5,4}) + " (4)");
        solution.add(new int[] {3,6});
        solution.add(new int[] {9,0});
        solution.add(new int[] {3,0});
        System.out.println(solution.count(new int[] {9,6}) + " (5)");
        solution.add(new int[] {0,2});
        solution.add(new int[] {1,1});
        solution.add(new int[] {0,1});
        System.out.println(solution.count(new int[] {1,2}) + " (10)");
        solution.add(new int[] {1,7});
        solution.add(new int[] {8,0});
        solution.add(new int[] {8,7});
        System.out.println(solution.count(new int[] {1,0}) + " (26)");
        solution.add(new int[] {2,7});
        solution.add(new int[] {4,5});
        solution.add(new int[] {2,5});
        System.out.println(solution.count(new int[] {4,7}) + " (8)");
        solution.add(new int[] {6,7});
        solution.add(new int[] {3,7});
        solution.add(new int[] {6,4});
        System.out.println(solution.count(new int[] {3,4}) + " (3)");
        solution.add(new int[] {10,2});
        solution.add(new int[] {2,10});
        solution.add(new int[] {2,2});
        System.out.println(solution.count(new int[] {10,10}) + " (7)");
        solution.add(new int[] {10,1});
        solution.add(new int[] {1,10});
        solution.add(new int[] {1,1});
        System.out.println(solution.count(new int[] {10,10}) + " (21)");
        solution.add(new int[] {2,10});
        solution.add(new int[] {2,9});
        solution.add(new int[] {3,9});
        System.out.println(solution.count(new int[] {3,10}) + " (20)");
        solution.add(new int[] {10,1});
        solution.add(new int[] {1,10});
        solution.add(new int[] {1,1});
        System.out.println(solution.count(new int[] {10,10}) + " (52)");
        solution.add(new int[] {10,4});
        solution.add(new int[] {10,3});
        solution.add(new int[] {9,4});
        System.out.println(solution.count(new int[] {9,3}) + " (6)");
        solution.add(new int[] {6,6});
        solution.add(new int[] {6,10});
        solution.add(new int[] {10,6});
        System.out.println(solution.count(new int[] {10,10}) + " (56)");
        solution.add(new int[] {9,7});
        solution.add(new int[] {4,7});
        solution.add(new int[] {9,2});
        System.out.println(solution.count(new int[] {4,2}) + " (2)");
        solution.add(new int[] {2,3});
        solution.add(new int[] {2,1});
        solution.add(new int[] {0,3});
        System.out.println(solution.count(new int[] {0,1}) + " (5)");
        solution.add(new int[] {2,8});
        solution.add(new int[] {10,8});
        solution.add(new int[] {2,0});
        System.out.println(solution.count(new int[] {10,0}) + " (17)");
        solution.add(new int[] {8,4});
        solution.add(new int[] {2,10});
        solution.add(new int[] {8,10});
        System.out.println(solution.count(new int[] {2,4}) + " (18)");
        solution.add(new int[] {0,0});
        solution.add(new int[] {9,9});
        solution.add(new int[] {0,9});
        System.out.println(solution.count(new int[] {9,0}) + " (13)");
        solution.add(new int[] {5,7});
        solution.add(new int[] {5,8});
        solution.add(new int[] {4,7});
        System.out.println(solution.count(new int[] {4,8}) + " (19)");
        solution.add(new int[] {10,10});
        solution.add(new int[] {10,1});
        solution.add(new int[] {1,1});
        System.out.println(solution.count(new int[] {1,10}) + " (102)");
        solution.add(new int[] {6,8});
        solution.add(new int[] {7,8});
        solution.add(new int[] {6,9});
        System.out.println(solution.count(new int[] {7,9}) + " (9)");
        solution.add(new int[] {4,6});
        solution.add(new int[] {1,6});
        solution.add(new int[] {4,3});
        System.out.println(solution.count(new int[] {1,3}) + " (2)");
        solution.add(new int[] {10,1});
        solution.add(new int[] {1,10});
        solution.add(new int[] {10,10});
        System.out.println(solution.count(new int[] {1,1}) + " (157)");
        solution.add(new int[] {7,7});
        solution.add(new int[] {7,10});
        solution.add(new int[] {4,7});
        System.out.println(solution.count(new int[] {4,10}) + " (23)");
        solution.add(new int[] {0,0});
        solution.add(new int[] {8,0});
        solution.add(new int[] {0,8});
        System.out.println(solution.count(new int[] {8,8}) + " (29)");
        solution.add(new int[] {3,5});
        solution.add(new int[] {2,4});
        solution.add(new int[] {3,4});
        System.out.println(solution.count(new int[] {2,5}) + " (23)");
        solution.add(new int[] {0,6});
        solution.add(new int[] {0,2});
        solution.add(new int[] {4,2});
        System.out.println(solution.count(new int[] {4,6}) + " (15)");
        solution.add(new int[] {5,2});
        solution.add(new int[] {9,6});
        solution.add(new int[] {9,2});
        System.out.println(solution.count(new int[] {5,6}) + " (24)");
        solution.add(new int[] {1,1});
        solution.add(new int[] {1,10});
        solution.add(new int[] {10,10});
        System.out.println(solution.count(new int[] {10,1}) + " (186)");
        solution.add(new int[] {7,5});
        solution.add(new int[] {2,0});
        solution.add(new int[] {2,5});
        System.out.println(solution.count(new int[] {7,0}) + " (12)");
        solution.add(new int[] {1,9});
        solution.add(new int[] {1,2});
        solution.add(new int[] {8,2});
        System.out.println(solution.count(new int[] {8,9}) + " (32)");
        solution.add(new int[] {3,8});
        solution.add(new int[] {3,3});
        solution.add(new int[] {8,3});
        System.out.println(solution.count(new int[] {8,8}) + " (36)");
        solution.add(new int[] {3,10});
        solution.add(new int[] {9,10});
        solution.add(new int[] {3,4});
        System.out.println(solution.count(new int[] {9,4}) + " (10)");
        solution.add(new int[] {0,2});
        solution.add(new int[] {0,10});
        solution.add(new int[] {8,10});
        System.out.println(solution.count(new int[] {8,2}) + " (35)");
        solution.add(new int[] {9,4});
        solution.add(new int[] {8,4});
        solution.add(new int[] {8,5});
        System.out.println(solution.count(new int[] {9,5}) + " (20)");
        solution.add(new int[] {9,8});
        solution.add(new int[] {4,3});
        solution.add(new int[] {4,8});
        System.out.println(solution.count(new int[] {9,3}) + " (43)");
        solution.add(new int[] {4,9});
        solution.add(new int[] {0,5});
        solution.add(new int[] {0,9});
        System.out.println(solution.count(new int[] {4,5}) + " (48)");
        solution.add(new int[] {1,3});
        solution.add(new int[] {3,5});
        solution.add(new int[] {1,5});
        System.out.println(solution.count(new int[] {3,3}) + " (35)");
        solution.add(new int[] {0,0});
        solution.add(new int[] {0,8});
        solution.add(new int[] {8,0});
        System.out.println(solution.count(new int[] {8,8}) + " (73)");
        solution.add(new int[] {2,8});
        solution.add(new int[] {10,0});
        solution.add(new int[] {10,8});
        System.out.println(solution.count(new int[] {2,0}) + " (59)");
        solution.add(new int[] {8,1});
        solution.add(new int[] {0,9});
        solution.add(new int[] {8,9});
        System.out.println(solution.count(new int[] {0,1}) + " (56)");
        solution.add(new int[] {4,9});
        solution.add(new int[] {4,6});
        solution.add(new int[] {1,9});
        System.out.println(solution.count(new int[] {1,6}) + " (72)");
        solution.add(new int[] {0,9});
        solution.add(new int[] {0,8});
        solution.add(new int[] {1,9});
        System.out.println(solution.count(new int[] {1,8}) + " (198)");
        solution.add(new int[] {5,1});
        solution.add(new int[] {5,6});
        solution.add(new int[] {10,1});
        System.out.println(solution.count(new int[] {10,6}) + " (37)");
        solution.add(new int[] {9,2});
        solution.add(new int[] {2,2});
        solution.add(new int[] {2,9});
        System.out.println(solution.count(new int[] {9,9}) + " (145)");
        solution.add(new int[] {5,5});
        solution.add(new int[] {8,5});
        solution.add(new int[] {5,8});
        System.out.println(solution.count(new int[] {8,8}) + " (130)");
        solution.add(new int[] {8,0});
        solution.add(new int[] {1,0});
        solution.add(new int[] {8,7});
        System.out.println(solution.count(new int[] {1,7}) + " (45)");
        solution.add(new int[] {8,2});
        solution.add(new int[] {5,5});
        solution.add(new int[] {5,2});
        System.out.println(solution.count(new int[] {8,5}) + " (68)");
        solution.add(new int[] {6,6});
        solution.add(new int[] {6,8});
        solution.add(new int[] {8,6});
        System.out.println(solution.count(new int[] {8,8}) + " (172)");
        solution.add(new int[] {2,10});
        solution.add(new int[] {10,2});
        solution.add(new int[] {2,2});
        System.out.println(solution.count(new int[] {10,10}) + " (281)");
        solution.add(new int[] {1,9});
        solution.add(new int[] {8,2});
        solution.add(new int[] {1,2});
        System.out.println(solution.count(new int[] {8,9}) + " (147)");
        solution.add(new int[] {7,4});
        solution.add(new int[] {7,2});
        solution.add(new int[] {9,4});
        System.out.println(solution.count(new int[] {9,2}) + " (53)");
        solution.add(new int[] {1,9});
        solution.add(new int[] {1,0});
        solution.add(new int[] {10,0});
        System.out.println(solution.count(new int[] {10,9}) + " (160)");
        solution.add(new int[] {2,10});
        solution.add(new int[] {2,3});
        solution.add(new int[] {9,10});
        System.out.println(solution.count(new int[] {9,3}) + " (105)");
        solution.add(new int[] {10,0});
        solution.add(new int[] {1,0});
        solution.add(new int[] {1,9});
        System.out.println(solution.count(new int[] {10,9}) + " (253)");
        solution.add(new int[] {8,10});
        solution.add(new int[] {1,10});
        solution.add(new int[] {1,3});
        System.out.println(solution.count(new int[] {8,3}) + " (82)");
        solution.add(new int[] {0,9});
        solution.add(new int[] {9,9});
        solution.add(new int[] {0,0});
        System.out.println(solution.count(new int[] {9,0}) + " (103)");
        solution.add(new int[] {7,9});
        solution.add(new int[] {8,9});
        solution.add(new int[] {7,8});
        System.out.println(solution.count(new int[] {8,8}) + " (248)");
        solution.add(new int[] {3,1});
        solution.add(new int[] {9,7});
        solution.add(new int[] {9,1});
        System.out.println(solution.count(new int[] {3,7}) + " (75)");
        solution.add(new int[] {5,9});
        solution.add(new int[] {6,9});
        solution.add(new int[] {5,8});
        System.out.println(solution.count(new int[] {6,8}) + " (86)");
        solution.add(new int[] {0,1});
        solution.add(new int[] {0,10});
        solution.add(new int[] {9,10});
        System.out.println(solution.count(new int[] {9,1}) + " (312)");
        solution.add(new int[] {8,0});
        solution.add(new int[] {8,2});
        solution.add(new int[] {10,2});
        System.out.println(solution.count(new int[] {10,0}) + " (301)");
        solution.add(new int[] {8,0});
        solution.add(new int[] {0,8});
        solution.add(new int[] {8,8});
        System.out.println(solution.count(new int[] {0,0}) + " (273)");
        solution.add(new int[] {6,7});
        solution.add(new int[] {5,8});
        solution.add(new int[] {5,7});
        System.out.println(solution.count(new int[] {6,8}) + " (119)");
        solution.add(new int[] {0,9});
        solution.add(new int[] {0,2});
        solution.add(new int[] {7,9});
        System.out.println(solution.count(new int[] {7,2}) + " (191)");
        solution.add(new int[] {5,0});
        solution.add(new int[] {5,5});
        solution.add(new int[] {10,0});
        System.out.println(solution.count(new int[] {10,5}) + " (61)");
        solution.add(new int[] {1,10});
        solution.add(new int[] {10,10});
        solution.add(new int[] {10,1});
        System.out.println(solution.count(new int[] {1,1}) + " (584)");
        solution.add(new int[] {9,2});
        solution.add(new int[] {9,10});
        solution.add(new int[] {1,2});
        System.out.println(solution.count(new int[] {1,10}) + " (696)");
        solution.add(new int[] {1,10});
        solution.add(new int[] {10,1});
        solution.add(new int[] {10,10});
        System.out.println(solution.count(new int[] {1,1}) + " (802)");
        solution.add(new int[] {9,9});
        solution.add(new int[] {0,9});
        solution.add(new int[] {0,0});
        System.out.println(solution.count(new int[] {9,0}) + " (293)");
        solution.add(new int[] {9,6});
        solution.add(new int[] {9,3});
        solution.add(new int[] {6,3});
        System.out.println(solution.count(new int[] {6,6}) + " (104)");
        solution.add(new int[] {10,4});
        solution.add(new int[] {6,0});
        solution.add(new int[] {10,0});
        System.out.println(solution.count(new int[] {6,4}) + " (114)");
        solution.add(new int[] {6,8});
        solution.add(new int[] {0,2});
        solution.add(new int[] {0,8});
        System.out.println(solution.count(new int[] {6,2}) + " (242)");
        solution.add(new int[] {7,9});
        solution.add(new int[] {0,9});
        solution.add(new int[] {7,2});
        System.out.println(solution.count(new int[] {0,2}) + " (259)");
        solution.add(new int[] {9,1});
        solution.add(new int[] {9,10});
        solution.add(new int[] {0,10});
        System.out.println(solution.count(new int[] {0,1}) + " (300)");
        solution.add(new int[] {10,0});
        solution.add(new int[] {10,9});
        solution.add(new int[] {1,9});
        System.out.println(solution.count(new int[] {1,0}) + " (465)");
        solution.add(new int[] {1,6});
        solution.add(new int[] {1,9});
        solution.add(new int[] {4,9});
        System.out.println(solution.count(new int[] {4,6}) + " (180)");
        solution.add(new int[] {0,8});
        solution.add(new int[] {1,9});
        solution.add(new int[] {0,9});
        System.out.println(solution.count(new int[] {1,8}) + " (1082)");
        solution.add(new int[] {1,1});
        solution.add(new int[] {9,1});
        solution.add(new int[] {1,9});
        System.out.println(solution.count(new int[] {9,9}) + " (697)");
        solution.add(new int[] {2,5});
        solution.add(new int[] {2,9});
        solution.add(new int[] {6,5});
        System.out.println(solution.count(new int[] {6,9}) + " (187)");
        solution.add(new int[] {7,3});
        solution.add(new int[] {2,3});
        solution.add(new int[] {2,8});
        System.out.println(solution.count(new int[] {7,8}) + " (113)");
        solution.add(new int[] {9,4});
        solution.add(new int[] {4,4});
        solution.add(new int[] {9,9});
        System.out.println(solution.count(new int[] {4,9}) + " (201)");
        solution.add(new int[] {4,4});
        solution.add(new int[] {2,4});
        solution.add(new int[] {4,2});
        System.out.println(solution.count(new int[] {2,2}) + " (520)");
        solution.add(new int[] {0,3});
        solution.add(new int[] {0,2});
        solution.add(new int[] {1,3});
        System.out.println(solution.count(new int[] {1,2}) + " (652)");
        solution.add(new int[] {10,9});
        solution.add(new int[] {10,2});
        solution.add(new int[] {3,2});
        System.out.println(solution.count(new int[] {3,9}) + " (197)");
        solution.add(new int[] {5,6});
        solution.add(new int[] {10,6});
        solution.add(new int[] {10,1});
        System.out.println(solution.count(new int[] {5,1}) + " (91)");
        solution.add(new int[] {9,0});
        solution.add(new int[] {0,9});
        solution.add(new int[] {9,9});
        System.out.println(solution.count(new int[] {0,0}) + " (670)");
        solution.add(new int[] {5,6});
        solution.add(new int[] {9,2});
        solution.add(new int[] {9,6});
        System.out.println(solution.count(new int[] {5,2}) + " (159)");
        solution.add(new int[] {3,3});
        solution.add(new int[] {10,3});
        solution.add(new int[] {10,10});
        System.out.println(solution.count(new int[] {3,10}) + " (189)");
        solution.add(new int[] {2,4});
        solution.add(new int[] {2,10});
        solution.add(new int[] {8,4});
        System.out.println(solution.count(new int[] {8,10}) + " (386)");
        solution.add(new int[] {4,9});
        solution.add(new int[] {1,9});
        solution.add(new int[] {4,6});
        System.out.println(solution.count(new int[] {1,6}) + " (403)");
        solution.add(new int[] {1,8});
        solution.add(new int[] {9,0});
        solution.add(new int[] {1,0});
        System.out.println(solution.count(new int[] {9,8}) + " (204)");
        solution.add(new int[] {10,3});
        solution.add(new int[] {5,8});
        solution.add(new int[] {5,3});
        System.out.println(solution.count(new int[] {10,8}) + " (301)");
        solution.add(new int[] {8,2});
        solution.add(new int[] {0,10});
        solution.add(new int[] {8,10});
        System.out.println(solution.count(new int[] {0,2}) + " (378)");
        solution.add(new int[] {9,0});
        solution.add(new int[] {2,7});
        solution.add(new int[] {9,7});
        System.out.println(solution.count(new int[] {2,0}) + " (314)");
        solution.add(new int[] {0,4});
        solution.add(new int[] {5,9});
        solution.add(new int[] {0,9});
        System.out.println(solution.count(new int[] {5,4}) + " (292)");
        solution.add(new int[] {5,3});
        solution.add(new int[] {10,3});
        solution.add(new int[] {5,8});
        System.out.println(solution.count(new int[] {10,8}) + " (352)");
        solution.add(new int[] {6,4});
        solution.add(new int[] {7,4});
        solution.add(new int[] {6,5});
        System.out.println(solution.count(new int[] {7,5}) + " (174)");
        solution.add(new int[] {9,1});
        solution.add(new int[] {0,1});
        solution.add(new int[] {9,10});
        System.out.println(solution.count(new int[] {0,10}) + " (2778)");
        solution.add(new int[] {5,10});
        solution.add(new int[] {5,7});
        solution.add(new int[] {8,7});
        System.out.println(solution.count(new int[] {8,10}) + " (473)");
        solution.add(new int[] {8,0});
        solution.add(new int[] {8,7});
        solution.add(new int[] {1,7});
        System.out.println(solution.count(new int[] {1,0}) + " (869)");
        solution.add(new int[] {1,1});
        solution.add(new int[] {9,9});
        solution.add(new int[] {1,9});
        System.out.println(solution.count(new int[] {9,1}) + " (1568)");
        solution.add(new int[] {3,1});
        solution.add(new int[] {3,5});
        solution.add(new int[] {7,5});
        System.out.println(solution.count(new int[] {7,1}) + " (190)");
        solution.add(new int[] {5,8});
        solution.add(new int[] {5,3});
        solution.add(new int[] {10,8});
        System.out.println(solution.count(new int[] {10,3}) + " (198)");
        solution.add(new int[] {0,9});
        solution.add(new int[] {2,7});
        solution.add(new int[] {2,9});
        System.out.println(solution.count(new int[] {0,7}) + " (342)");
        solution.add(new int[] {9,3});
        solution.add(new int[] {9,7});
        solution.add(new int[] {5,3});
        System.out.println(solution.count(new int[] {5,7}) + " (286)");
        solution.add(new int[] {0,0});
        solution.add(new int[] {9,0});
        solution.add(new int[] {9,9});
        System.out.println(solution.count(new int[] {0,9}) + " (1062)");
        solution.add(new int[] {6,4});
        solution.add(new int[] {4,2});
        solution.add(new int[] {4,4});
        System.out.println(solution.count(new int[] {6,2}) + " (475)");
        solution.add(new int[] {1,9});
        solution.add(new int[] {1,5});
        solution.add(new int[] {5,5});
        System.out.println(solution.count(new int[] {5,9}) + " (354)");
        solution.add(new int[] {7,7});
        solution.add(new int[] {0,7});
        solution.add(new int[] {0,0});
        System.out.println(solution.count(new int[] {7,0}) + " (174)");
        solution.add(new int[] {1,3});
        solution.add(new int[] {1,9});
        solution.add(new int[] {7,3});
        System.out.println(solution.count(new int[] {7,9}) + " (574)");
        solution.add(new int[] {0,9});
        solution.add(new int[] {9,9});
        solution.add(new int[] {9,0});
        System.out.println(solution.count(new int[] {0,0}) + " (1605)");
        solution.add(new int[] {1,8});
        solution.add(new int[] {3,6});
        solution.add(new int[] {3,8});
        System.out.println(solution.count(new int[] {1,6}) + " (547)");
    }

    public static void main(final String[] args) {
        test1();
        test2();
    }
}
